# Generated by Django 5.0.1 on 2024-01-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('example', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lead_name', models.CharField(max_length=100)),
                ('count_users', models.IntegerField()),
                ('users', models.ManyToManyField(to='example.user')),
            ],
        ),
    ]
